### Récupérer tous les actors
GET http://localhost:80/api/actors

### Récupérer un actor
GET http://localhost:80/api/actors/1

### Créer un actor
POST http://localhost:80/api/actors
Content-Type: application/json

{
    "data": {
        "firstName": "Aaron",
        "lastName": "Pierre"
    }
}

### Créer un actor
POST http://localhost:80/api/actors
Content-Type: application/json

{
    "data": {
        "firstName": "Kelvin",
        "lastName": "Harrison Jr."
    }
}

### Créer un actor
POST http://localhost:80/api/actors
Content-Type: application/json

{
    "data": {
        "firstName": "Tiffany",
        "lastName": "Boone"
    }
}

### Créer un actor
POST http://localhost:80/api/actors
Content-Type: application/json

{
    "data": {
        "firstName": "Emma",
        "lastName": "Watson"
    }
}

### Modifier un actor
PUT http://localhost:80/api/actors/1
Content-Type: application/json

{
    "data": {
        "firstName": "Aaron",
        "lastName": "Pierre"
    }
}

### Supprimer un actor
DELETE http://localhost:80/api/actors/1