### Créer un user
POST http://localhost:40/api/auth/local/register
Content-Type: application/json

{
    "data": {
        "login": "lea.schmidt@gmail.com",
        "password": "lea1234"
    }
}



### Créer un user
POST http://localhost:40/api/auth/local
Content-Type: application/json

{
    "data": {
        "login": "lea.schmidt@gmail.com",
        "password": "lea1234"
    }
}
