### Récupère tous les classes
GET http://localhost:40/api/classes
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJsZWEuc2NobWlkdEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQ4UjIyem5uVDFRM1hPWWY3bVJtN1hlNDduSy8vLms2N3gza1pmYktmVnMvZktUU1Zib2Q2ZSIsImNyZWF0ZWRBdCI6IjIwMjUtMDItMDZUMDk6MTU6MjQuNjg1WiIsInVwZGF0ZWRBdCI6IjIwMjUtMDItMDZUMDk6MTU6MjQuNjg1WiIsImlhdCI6MTczODgzNTUzM30.zBpbZ8XkThf1GPOYFkBJzpDyRSnPJVidXIqvdlQLt1Y


### Ajoute une classe
POST http://localhost:40/api/classes
Content-Type: application/json

{
    "nom": "Bachelor Développeur Web"
}